In [1]:
import torch

In [2]:
x=torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [3]:
x[1, 1, 1]

tensor(10)

In [7]:
# slicing the tensor 
#slicing the elements from 6 to 11

x[1, 0: 2, 0:3]#in the second block, we take rows 1 and 2, which are in columns 1, 2 and 3

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [8]:
#or, 
x[1, :, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])